

import os

def colsumLists():
    return ({"ID",
             "PROCESS_ID",
             "PARTNER_NAME",
             "DIRECTION",
             "INTERCHANGE_SENDER_ID",
             "INTERCHANGE_RECEIVER_ID",
             "INTERCHANGE_CONTROL_NUMBER",
             "GROUP_SENDER_ID",
             "GROUP_RECIEVER_ID",
             "GROUP_CONTROL_NUMBER",
             "TRANSACTION_CONTROL_NUMBER",
             "TRANSACTION_TYPE",
             "TRANSACTION_ID",
             "TRANSACTION_STATUS",
             "FA_STATUS",
             "RECV_FILENAME",
             "ECV_FILE_ARCHIVE_PATH",
             "SEND_FILENAME",
             "SEND_FILE_ARCHIVE_PATH",
             "APPLICATIONDOC_NUM",
             "PO_DATE",
             "PURCHASE_ORDER_NUMBER",
             "INVOICE_DATE",
             "INVOICE_NUMBER",
             "ASN_NUMBER",
             "ASN_DATE",
             "PO_AMOUNT",
             "INVOICE_AMOUNT",
             "REF_VALUE1",
             "REF_NAME1",
             "REF_VALUE2",
             "REF_NAME2",
             "REF_VALUE3",
             "REF_NAME3",
             "CREATE_DATE_TIME",
             "LAST_UPDATE_DATE_TIME"})